-- Fase 34 — migração dos 114 produtos de marca da Fase 30 para food_products.
-- Gerado por scripts/migrate-phase30-products.js — FICHEIRO VERSIONADO, não
-- precisa de ser regenerado para repetir/auditar esta operação no futuro.
--
-- Todos entram como 'pending' — nenhum tem uma fonte INDIVIDUAL verificável
-- guardada (página oficial, rótulo fotografado, ou ficha da Open Food Facts
-- corretamente associada a esse produto específico), por isso source_url
-- fica null em todos. O link do commit onde foram originalmente revistos
-- (https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9) vai só em
-- internal_note, como nota de auditoria interna — NUNCA conta como fonte
-- nutricional nem é mostrado ao aluno. source_type = 'legacy_phase30'.
-- ean fica por preencher (melhor null do que um código incerto).
-- Nenhum retalhista é associado nesta migração, para não mudar o nome de
-- nenhum produto já usado em planos de alunos (ver ponto 4 no script).
--
-- Aprova cada um no Catálogo à medida que confirmares uma fonte real —
-- até lá, o FOOD_DB atual no código continua a ser o fallback ativo (estes
-- produtos só chegam à app via loadFoodProducts() depois de 'verified').

insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Pão de forma 100% integral', 'Mercadona', 'cereais', '100g', 250, 11.3, 36, 4.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Pão de forma com sementes e pevides', 'Hacendado', 'cereais', '100g', 290.2, 11, 38, 9.3, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Pão de forma branco', 'Hacendado', 'cereais', '100g', 250, 9, 46, 2.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Penne Rigate', 'Barilla', 'cereais', '100g', 359, 13, 71, 2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Esparguete integral', 'Milaneza', 'cereais', '100g', 348, 13, 66, 1.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Esparguete', 'Milaneza', 'cereais', '100g', 359, 13, 71, 1.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Fusilli de trigo integral', 'Continente', 'cereais', '100g', 135, 4.4, 26, 0.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Esparguete de trigo integral', 'Continente', 'cereais', '100g', 135, 4.4, 26, 1.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Arroz integral longo', 'Hacendado', 'cereais', '100g', 350, 7.6, 72, 2.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Arroz basmati', 'Hacendado', 'cereais', '100g', 355, 9, 78, 0.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Arroz carolino', 'Continente', 'cereais', '100g', 350, 6.8, 78, 1.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Arroz vaporizado', 'Continente', 'cereais', '100g', 355, 7.5, 78, 1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Arroz basmati', 'Pingo Doce', 'cereais', '100g', 361, 7.7, 79, 1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Arroz integral', 'Pingo Doce', 'cereais', '100g', 349, 7, 71, 3.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Flocos de aveia extra suaves', 'Brüggen', 'cereais', '100g', 375, 14, 59, 7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Muesli crocante', 'Mercadona', 'cereais', '100g', 401, 8.8, 52, 12, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Farinha fina de milho', 'Hacendado', 'cereais', '100g', 359, 0.3, 90, 0.5, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Farinha de milho branco pré-cozida', 'Hacendado', 'cereais', '100g', 357, 9.2, 75, 1.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Farinha branca de neve fina', 'Branca de Neve', 'cereais', '100g', 349, 9, 74, 1.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Farinha de aveia integral', 'Seara', 'cereais', '100g', 370, 14, 56, 7.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Farinha de trigo tipo 55 sem fermento', 'Pingo Doce', 'cereais', '100g', 363, 10, 76, 1.3, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Iogurte grego natural ligeiro', 'Continente Equilíbrio', 'laticinios', '100g', 55, 5.3, 3.9, 2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Iogurte grego natural', 'Oikos', 'laticinios', '100g', 62.7, 3.4, 4.4, 7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Iogurte proteico de baunilha', 'YoPro Danone', 'laticinios', '100g', 53.3, 9.4, 3.6, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Iogurte proteico com manga e maracujá 0%', 'Mercadona', 'laticinios', '100g', 56.7, 8.3, 5.8, 0.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Iogurte com frutos do bosque', 'Mercadona', 'laticinios', '100g', 98, 3.7, 13.7, 3.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Iogurte 0% com fruta', 'Mercadona', 'laticinios', '100g', 45, 4.5, 6.5, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Ricotta', 'Mercadona', 'laticinios', '100g', 179, 9.7, 3.8, 14, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Mozzarella', 'Hacendado', 'laticinios', '100g', 202.4, 17, 2, 14, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Grana Padano', 'Hacendado', 'laticinios', '100g', 398, 33, 0, 29, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Queijo feta', 'Mercadona', 'laticinios', '100g', 276.7, 16, 1, 23.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Queijo creme suave', 'Mercadona', 'laticinios', '100g', 244, 4.2, 3.7, 23, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Leite meio-gordo', 'Mimosa', 'laticinios', '100g', 48, 3.4, 4.9, 1.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Leite meio-gordo', 'Continente', 'laticinios', '100g', 48, 3.4, 4.9, 1.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Leite magro', 'Continente Equilíbrio', 'laticinios', '100g', 35, 3.5, 5, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Leite meio-gordo UHT', 'Pingo Doce', 'laticinios', '100g', 49, 3.4, 5.3, 1.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Leite gordo', 'Mimosa', 'laticinios', '100g', 63.2, 3.2, 4.7, 3.5, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Leite meio-gordo sem lactose', 'Mimosa', 'laticinios', '100g', 47, 3.3, 4.9, 1.6, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bebida de aveia', 'Liquats Vegetals', 'laticinios', '100g', 47, 1.6, 8.2, 0.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bebida de soja', 'Mercadona', 'laticinios', '100g', 35, 3.4, 0.8, 1.9, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Água de coco', 'Mercadona', 'laticinios', '100g', 20, 0, 5, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Peito de peru fatiado', 'Continente', 'carnes', '100g', 92.3, 13, 4.7, 2.3, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Salsichas tipo Frankfurt', 'Nobre', 'carnes', '100g', 156, 10, 4.2, 11, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Peito de frango fatias finas', 'Campofrio', 'carnes', '100g', 83, 14, 3.8, 1.3, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bacon em tiras fumado', 'Dulano', 'carnes', '100g', 278, 15, 0.5, 24, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Fiambre de frango', 'Monells', 'carnes', '100g', 156, 11, 10, 8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Salsichas de aves', 'Continente', 'carnes', '100g', 151, 10, 4, 11, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bacon fumado', 'Continente', 'carnes', '100g', 259, 17, 0.6, 21, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Fiambre da pá', 'Pingo Doce', 'carnes', '100g', 98, 14, 1.4, 4, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Asas de frango crocantes', 'PorSi', 'carnes', '100g', 163, 16, 2, 10, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Peito de peru', 'Dia', 'carnes', '100g', 88, 15.5, 2, 2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bife de frango', 'Pingo Doce', 'carnes', '100g', 98, 23.6, 0, 0.4, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Sardinhas portuguesas em azeite', 'Ramirez', 'carnes', '100g', 258, 22.2, 0, 18.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Atum posta ao natural', 'Pingo Doce', 'carnes', '100g', 100.9, 23, 0, 0.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Atum posta em óleo de girassol', 'Pingo Doce', 'carnes', '100g', 200, 25, 0, 11, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Sardinha enlatada em azeite', 'Continente', 'carnes', '100g', 212, 23, 0.5, 13, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Varinhas de pescada', 'Ocean Sea', 'carnes', '100g', 185, 11.4, 16, 8.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Fatias de presunto', 'Nobre', 'carnes', '100g', 212, 30, 0.5, 10, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Ovos frescos classe M', 'Pingo Doce', 'carnes', '100g', 131, 13, 1, 8.3, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Ovos frescos', 'Continente', 'carnes', '100g', 141, 12, 0.7, 10, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Clara de ovo', 'Continente', 'carnes', '100g', 47, 11, 0.7, 0.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Ameixas secas sem caroço', 'Mercadona', 'fruta', '100g', 240, 2.2, 57, 0.4, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Tâmaras secas sem caroço', 'Mercadona', 'fruta', '100g', 298, 2, 76.4, 0.5, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Tâmara seca', 'Continente', 'fruta', '100g', 321, 2.3, 74, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Tâmara seca com caroço', 'Pingo Doce', 'fruta', '100g', 321, 0.1, 73.8, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bagas goji secas', 'Bio', 'fruta', '100g', 328, 13, 66, 1.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Mirtilos', 'Pingo Doce', 'fruta', '100g', 52, 0.7, 11, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Mistura de frutos vermelhos secos', 'Origens', 'fruta', '100g', 44, 0.4, 9, 0.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Tomate pelado em pedaços', 'Hacendado', 'vegetais', '100g', 31, 1.1, 6, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Cenouras', 'Continente', 'vegetais', '100g', 25, 0.6, 4.4, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Polpa de tomate', 'Pingo Doce', 'vegetais', '100g', 37, 1.7, 6.3, 0.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Polpa de tomate', 'Continente', 'vegetais', '100g', 38, 1.8, 6.6, 0.5, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Tomate em pedaços', 'Pingo Doce', 'vegetais', '100g', 25, 0.6, 2.8, 0.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Feijão verde', 'Compal', 'vegetais', '100g', 14, 0.9, 1.8, 0.5, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Tomate pelado inteiro', 'Pingo Doce', 'vegetais', '100g', 18, 0.7, 2.7, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Pimentos assados vermelhos e verdes', 'Hacendado', 'vegetais', '100g', 30, 1, 5.2, 0.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Azeite virgem extra', 'Hacendado', 'gorduras', '100g', 824, 0, 0, 91, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Azeite virgem extra', 'Pingo Doce', 'gorduras', '100g', 819, 0, 0, 91, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Azeite', 'Oliveira da Serra', 'gorduras', '100g', 822, 0, 0, 91, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Azeite Gallo', 'Gallo', 'gorduras', '100g', 819, 0, 0, 91, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Azeite', 'Continente', 'gorduras', '100g', 821, 0, 0, 91.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Azeite virgem extra', 'Herdade do Esporão', 'gorduras', '100g', 821, 0, 0, 91.2, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Óleo de coco virgem', 'Mercadona', 'gorduras', '100g', 900, 0, 0, 100, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Óleo de girassol', 'Fula', 'gorduras', '100g', 826, 0, 0, 92, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Óleo alimentar', 'Pingo Doce', 'gorduras', '100g', 828, 0, 0, 92, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Creme vegetal para barrar', 'Pingo Doce', 'gorduras', '100g', 450, 0, 0, 50, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Creme vegetal para barrar', 'Continente', 'gorduras', '100g', 450, 0, 0, 50, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Margarina vegetal', 'Vaqueiro', 'gorduras', '100g', 677, 0.5, 0.5, 75, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Nutella — creme de avelã e cacau', 'Nutella', 'gorduras', '100g', 539, 6.3, 57.5, 30.9, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Manteiga de amendoim 100%', 'Mercadona', 'gorduras', '100g', 606.7, 30, 12, 46.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Guacamole', 'Mercadona', 'gorduras', '100g', 149, 1.9, 2, 13.7, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Hummus clássico', 'Hacendado', 'gorduras', '100g', 311, 6, 11.1, 25.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Manteiga de amendoim cremosa', 'Maribel', 'gorduras', '100g', 646.7, 27, 10, 53, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Manteiga tradicional com sal', 'Mimosa', 'gorduras', '100g', 743, 0.6, 0.7, 82, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Nozes', 'Dia', 'gorduras', '100g', 674, 19.9, 3.8, 62.4, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Caju', 'Continente', 'gorduras', '100g', 619, 23, 18.2, 48.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Noz em metades', 'Continente', 'gorduras', '100g', 716, 15, 14, 65, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Nuggets de frango', 'Mercadona', 'snacks', '100g', 230, 10.4, 16.6, 13.4, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Pringles original', 'Pringles', 'snacks', '100g', 528, 6.2, 54, 31, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Sumol de laranja', 'Sumol', 'snacks', '100g', 30, 0, 7.5, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Guaraná Antarctica', 'Guaraná Antarctica', 'snacks', '100g', 40, 0, 10, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Coca-Cola original', 'Coca-Cola', 'snacks', '100g', 42, 0, 10.6, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Coca-Cola zero', 'Coca-Cola', 'snacks', '100g', 0.3, 0, 0, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Chocolate de leite', 'Milka', 'snacks', '100g', 539, 6.5, 57, 31, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Chocolate negro 72%', 'Mercadona', 'snacks', '100g', 568, 10, 32, 42, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Toblerone', 'Mondelez', 'snacks', '100g', 535, 5.6, 60.5, 29.5, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bolachas Nutella de avelã e cacau', 'Ferrero', 'snacks', '100g', 515, 7.9, 64, 24.8, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Bolacha Maria 100% integral', 'Mercadona', 'snacks', '100g', 410, 8.7, 66, 10, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Digestive de aveia', 'Mercadona', 'snacks', '100g', 477, 7.5, 61, 21, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Batatas fritas ao forno com sal', 'Lay''s', 'snacks', '100g', 442, 5.9, 73, 13, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Batatas fritas originais', 'Lay''s', 'snacks', '100g', 520, 6.2, 53.3, 31.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Rebuçados de eucalipto e mentol 0% açúcar', 'Hacendado', 'snacks', '100g', 250, 0.7, 97, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Sortido de gomas', 'Pingo Doce', 'snacks', '100g', 315, 4.1, 74.7, 0.1, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
insert into food_products (name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('Compota de morango 0% açúcar', 'Mercadona', 'snacks', '100g', 40, 0.6, 11.5, 0, null, 'Migrado do código (Fase 30) sem fonte individual guardada — ver https://github.com/tiagojvlourenco/plano-evolve/commit/e393fa9', 'legacy_phase30', 'pending');
