-- Fase 35 — 30 produtos Intermarché (Intermarché, Pâturages, Chabrior, Top Budget, Marque Repère) vendidos em Portugal (Open Food Facts).
-- Nomes traduzidos para português à mão. Todos pending (source_type open_food_facts, source_url individual). internal_note assinala dados duvidosos.

insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260265961', 'Leite com chocolate', 'Pâturages', 'laticinios', '100g', 73, 3.3, 12, 1.2, 'https://world.openfoodfacts.org/product/5604260265961', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260280506', 'Iogurte estilo grego stracciatella', 'Pâturages', 'laticinios', '100g', 146, 2.5, 15, 8.3, 'https://world.openfoodfacts.org/product/5604260280506', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260283415', 'Frutimax de ananás', 'Pâturages', 'laticinios', '100g', 89, 3, 13, 2.7, 'https://world.openfoodfacts.org/product/5604260283415', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260276042', 'Waffles', 'Chabrior', 'snacks', '100g', 422, 9.8, 51.3, 20.2, 'https://world.openfoodfacts.org/product/5604260276042', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260283422', 'Frutimax de alperce e pêssego', 'Pâturages', 'laticinios', '100g', 111, 3.8, 17, 3.4, 'https://world.openfoodfacts.org/product/5604260283422', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260277636', 'Amêndoas lisas coloridas', 'Intermarché', 'gorduras', '100g', 420, 3.6, 85, 6.9, 'https://world.openfoodfacts.org/product/5604260277636', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260276813', 'Iogurte grego de amora e framboesa', 'Pâturages', 'laticinios', '100g', 143, 2.4, 17.4, 7.1, 'https://world.openfoodfacts.org/product/5604260276813', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260162789', 'Natas UHT light', 'Pâturages', 'laticinios', '100g', 206, 2.8, 3.8, 20, 'https://world.openfoodfacts.org/product/5604260162789', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260269877', 'Crack Star cereais com mel', 'Chabrior', 'cereais', '100g', 388, 6, 85, 2.2, 'https://world.openfoodfacts.org/product/5604260269877', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260273102', 'Bolacha relevo com mel e coco', 'Chabrior', 'snacks', '100g', 157, 6, 70, 18, 'https://world.openfoodfacts.org/product/5604260273102', 'kcal (157) incoerente com os macros (≈466 kcal) — confirmar no rótulo.', 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260276721', 'Gelatina sabor morango (preparada)', 'Chabrior', 'snacks', '100g', 9, 2.2, 0, 0, 'https://world.openfoodfacts.org/product/5604260276721', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260277001', 'Gelatina sabor morango (em pó)', 'Chabrior', 'snacks', '100g', 394, 11, 87, 0.5, 'https://world.openfoodfacts.org/product/5604260277001', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260276738', 'Gelatina sabor ananás (preparada)', 'Chabrior', 'snacks', '100g', 9, 2.2, 0, 0, 'https://world.openfoodfacts.org/product/5604260276738', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260056552', 'Pão especial para cachorro', 'Chabrior', 'cereais', '100g', 282, 9.8, 50, 4.2, 'https://world.openfoodfacts.org/product/5604260056552', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260257485', 'Leite UHT magro', 'Top Budget', 'laticinios', '100g', 33, 3.2, 4.8, 0.1, 'https://world.openfoodfacts.org/product/5604260257485', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260257492', 'Leite UHT meio-gordo', 'Top Budget', 'laticinios', '100g', 48, 3.4, 4.9, 1.6, 'https://world.openfoodfacts.org/product/5604260257492', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260270989', 'Água de nascente', 'Top Budget', 'snacks', '100g', 0, 0, 0, 0, 'https://world.openfoodfacts.org/product/5604260270989', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260283828', 'Atum posta em óleo vegetal', 'Top Budget', 'carnes', '100g', 191, 25, 0.5, 10, 'https://world.openfoodfacts.org/product/5604260283828', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260129409', 'Queijo Gouda', 'Top Budget', 'laticinios', '100g', 354, 24, 0.5, 29, 'https://world.openfoodfacts.org/product/5604260129409', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('5604260167029', 'Queijo flamengo fatiado', 'Top Budget', 'laticinios', '100g', 341, 25, 1.7, 26, 'https://world.openfoodfacts.org/product/5604260167029', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('3564700838952', 'Cappuccino sabor baunilha latte', 'Marque Repère', 'snacks', '100g', 409, 8.1, 74, 7.1, 'https://world.openfoodfacts.org/product/3564700838952', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('3564700883013', 'Mini sablés de cereais', 'Marque Repère', 'snacks', '100g', 500, 6.4, 63, 24, 'https://world.openfoodfacts.org/product/3564700883013', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('3564700415085', 'Pote de creme de chocolate', 'Marque Repère', 'laticinios', '100g', 165, 3.4, 19.8, 7.8, 'https://world.openfoodfacts.org/product/3564700415085', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560590243466', 'Ravioli de 4 queijos', 'Marque Repère', 'cereais', '100g', 289, 12, 37, 10, 'https://world.openfoodfacts.org/product/0560590243466', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560120078957', 'Creme de ovos e caramelo', 'Marque Repère', 'laticinios', '100g', 164, 3.8, 24, 6.1, 'https://world.openfoodfacts.org/product/0560120078957', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560460655092', 'Milho com 2 pimentos', 'Marque Repère', 'vegetais', '100g', 72, 2.6, 10, 1.8, 'https://world.openfoodfacts.org/product/0560460655092', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560281571120', 'Arroz cantonês', 'Marque Repère', 'cereais', '100g', 125, 5.1, 21, 2.2, 'https://world.openfoodfacts.org/product/0560281571120', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560590013274', 'Feijão vermelho', 'Marque Repère', 'vegetais', '100g', 96, 7.2, 12, 0.7, 'https://world.openfoodfacts.org/product/0560590013274', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560560603832', 'Bûche fondante (queijo de cabra)', 'Marque Repère', 'laticinios', '100g', 279, 18, 0.5, 23, 'https://world.openfoodfacts.org/product/0560560603832', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
insert into food_products (ean, name, brand, food_group, nutrition_basis, kcal, protein, carbs, fat, source_url, internal_note, source_type, verification_status) values ('0560020049262', 'Salsifis', 'Marque Repère', 'vegetais', '100g', 28, 1.1, 4.1, 0.5, 'https://world.openfoodfacts.org/product/0560020049262', null, 'open_food_facts', 'pending') on conflict (ean) do nothing;
