-- Fase 35 — quarta revisão: valores confirmados no site do Continente (ficha do produto, EAN coincidente) e do Auchan.
-- Continente: 15 produtos, nome real e valores por 100 g/ml do próprio supermercado. Auchan: atum em posta em óleo vegetal (site: 234 kcal, 27 g proteína, 14 g gordura; EAN do site diferente do da Open Food Facts — mesmo produto/denominação).
update food_products set name = 'Patê de morcela da Beira e maçã Reineta', food_group = 'carnes', kcal = 167, protein = 7.4, carbs = 5.9, fat = 7.8, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312105244' and verification_status = 'pending';
update food_products set name = 'Iogurte líquido +Proteína de morango', food_group = 'laticinios', kcal = 50, protein = 7.1, carbs = 4.4, fat = 0.4, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312511939' and verification_status = 'pending';
update food_products set name = 'Batatas fritas onduladas sabor ketchup', food_group = 'snacks', kcal = 538, protein = 6.7, carbs = 51, fat = 33, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312077053' and verification_status = 'pending';
update food_products set name = 'Bolachas digestivas', food_group = 'snacks', kcal = 483, protein = 6, carbs = 66, fat = 21, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312061977' and verification_status = 'pending';
update food_products set name = 'Bolachas recheadas de baunilha', food_group = 'snacks', kcal = 491, protein = 4.5, carbs = 70, fat = 21, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312070078' and verification_status = 'pending';
update food_products set name = 'Muesli crunchy de frutos secos', food_group = 'cereais', kcal = 456, protein = 10, carbs = 60.2, fat = 17.8, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312069652' and verification_status = 'pending';
update food_products set name = 'Pipocas doces (balde)', food_group = 'snacks', kcal = 481, protein = 7.5, carbs = 59, fat = 22, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312074694' and verification_status = 'pending';
update food_products set name = 'Batatas fritas onduladas sabor presunto', food_group = 'snacks', kcal = 517, protein = 6.5, carbs = 53.1, fat = 30, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312002833' and verification_status = 'pending';
update food_products set name = 'Batata-doce frita', food_group = 'snacks', kcal = 566, protein = 3.3, carbs = 45, fat = 40.2, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312101048' and verification_status = 'pending';
update food_products set name = 'Iogurte skyr de mirtilo', food_group = 'laticinios', kcal = 47, protein = 7.5, carbs = 3.6, fat = 0, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312509578' and verification_status = 'pending';
update food_products set name = 'Iogurte com pedaços Super Breakfast de frutos vermelhos, muesli e chia', food_group = 'laticinios', kcal = 62, protein = 4.9, carbs = 6.1, fat = 1.9, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312516316' and verification_status = 'pending';
update food_products set name = 'Bolacha 5 cereais e framboesa', food_group = 'snacks', kcal = 430, protein = 7, carbs = 60.7, fat = 16.3, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312100522' and verification_status = 'pending';
update food_products set name = 'Gelado de morango', food_group = 'snacks', kcal = 186, protein = 0.8, carbs = 34, fat = 5, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312508311' and verification_status = 'pending';
update food_products set name = 'Néctar de uva Merlot', food_group = 'snacks', kcal = 47, protein = 0.2, carbs = 11, fat = 0.1, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312090960' and verification_status = 'pending';
update food_products set name = 'Gelado Nuts for Cups', food_group = 'snacks', kcal = 294, protein = 6.9, carbs = 27, fat = 17.3, internal_note = 'Valores confirmados no site do Continente.', verification_status = 'verified', verified_at = now() where ean = '5601312516187' and verification_status = 'pending';
update food_products set name = 'Atum em posta em óleo vegetal', food_group = 'carnes', kcal = 234, protein = 27, carbs = 0, fat = 14, internal_note = 'Valores do site do Auchan para o produto equivalente (EAN do site diferente).', verification_status = 'verified', verified_at = now() where ean = '5601002060105' and verification_status = 'pending';
update food_products set name = 'Atum em posta em óleo vegetal', food_group = 'carnes', kcal = 234, protein = 27, carbs = 0, fat = 14, internal_note = 'Valores do site do Auchan para o produto equivalente (EAN do site diferente).', verification_status = 'verified', verified_at = now() where ean = '5601002046116' and verification_status = 'pending';
select verification_status, source_type, count(*) from food_products group by 1,2 order by 1,2;
